#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# shellcheck disable=SC2086
function log() {
    echo "[Mount] ${1}"
}
IFS=$'\n'
filter="$1"
config=/config/rclone/rclone-docker.conf
#rclone listremotes | gawk "$filter"
mapfile -t mounts < <(eval mclone listremotes --config=${config} | grep "$filter" | sed -e 's/[GDSA00-99C:]//g' | sed '/^$/d')
## function source end

if [[ "$(command -v fusermount | wc -l)" != "1" ]]; then
   apk add fuser fuse-dev -q 
   log " > fuser and fusermount reinstalled "
fi

log "-> Stop mergerfs <-"
kill -9 $(pgrep mergerfs)

log "-> Stopping the mounts <-"
for i in ${mounts[@]}; do
    log "-> Stop Mounting $i <-"
    pids="$(ps -ef | grep '$i-mount.sh' | head -n 1 | grep -v grep | awk '{print $1}')"
    kill -9 $pids 
    sleep 2
    fusermount -uz /mnt/drive-$i
    sleep 2
    fusermount -uz /mnt/unionfs
    sleep 2
    find /mnt/drive-$i -type d -empty -delete
    sleep 2
    find /mnt/unionfs -type d -empty -delete
done
sleep 10
