#!/usr/bin/with-contenv bash
# shellcheck shell=bash
function log() {
echo "[Mount] ${1}"
}
source /config/env/rclone.env
echo "
-------------------------------------------------------
   RCLONE ENVIROMENTS
-------------------------------------------------------
   ## USER VALUES
   PUID                           ${PUID}
   PGID                           ${PGID}
   TIMEZONE                       ${TZ}

   ## RCLONE - SETTINGS
   POLL_INTERVAL                  ${POLL_INTERVAL:-30s}
   UMASK                          ${UMASK:-002}
   DIR_CACHE_TIME                 ${DIR_CACHE_TIME:-8760h}
   BUFFER_SIZE                    ${BUFFER_SIZE:-16M}
   TMPRCLONE                      ${TMPRCLONE:-/mnt/rclone_cache}
   UAGENT                         ${UAGENT:-MCLONE}
   MAX_READ_AHEAD                 ${MAX_READ_AHEAD:-2G}

   ## VFS - SETTINGS
   VFS_CACHE_POLL_INTERVAL        ${VFS_CACHE_POLL_INTERVAL:-15s}
   VFS_READ_CHUNK_SIZE            ${VFS_READ_CHUNK_SIZE:-32M}
   VFS_CACHE_MAX_AGE              ${VFS_CACHE_MAX_AGE:-72h}
   VFS_READ_CHUNK_SIZE_LIMIT      ${VFS_READ_CHUNK_SIZE_LIMIT:-1024M}
   VFS_CACHE_MODE                 ${VFS_CACHE_MODE:-full}
   VFS_CACHE_MAX_SIZE             ${VFS_CACHE_MAX_SIZE:-100G}
   VFS_READ_AHEAD                 ${VFS_READ_AHEAD:-1G}

   ## LOG - SETTINGS 
   LOGLEVEL                       ${LOGLEVEL}
   LOGLEVEL_RC                    ${LOGLEVEL_RC}

   ## RC-CONTROLLE
   RC_ADDRESS                     ${RC_ADDRESS}
   RC_USER                        ${RC_USER}
   RC_PASSWORD                    ${RC_PASSWORD}
"
##### FOLDER START #####
SMOUNT=/config/scripts
SRC=/config/rc-refresh
SDOWN=/mnt/downloads
SUNION=/mnt/unionfs
TMPRCLONE=${TMPRCLONE}
LOGS=/config/logs
chown -hR abc:abc ${LOGS} && chmod -R 775 ${LOGS}
chown -hR abc:abc ${SRC} && chmod -R 775 ${SRC}
chown -hR abc:abc ${SMOUNT} && chmod -R 775 ${SMOUNT}
##### FOLDER END #####
rm -rf /tmp/rclone-mount.file && touch /tmp/rclone-mount.file
config=/config/rclone/rclone-docker.conf
##### RUN MOUNT #####
if [[ ! -d ${TMPRCLONE} ]];then mkdir -p ${TMPRCLONE} && chown -hR abc:abc ${TMPRCLONE}  && chmod -R 775 ${TMPRCLONE};fi
if [[ ! -d "/mnt/remotes" ]];then mkdir -p /mnt/remotes && chown -hR abc:abc /mnt/remotes && chmod -R 775 /mnt/remotes;fi
if [[ ! -d "/mnt/unionfs" ]];then mkdir -p ${SUNION} && chown -hR abc:abc ${SUNION} && chmod -R 775 ${SUNION};fi
if [[ -f ${SMOUNT}/union-mount.sh ]];then rm -rf ${SMOUNT}/union-mount.sh;fi
if [[ -f ${SRC}/union-rc-file.sh ]];then rm -rf ${SRC}/union-rc-file.sh;fi
truncate -s 0 /config/logs/**.log >> /dev/null
echo -n "/mnt/downloads=RW:/mnt/remotes=RW" >>/tmp/rclone-mount.file
cat <<'EOF' > ${SMOUNT}/union-mount.sh
#!/usr/bin/with-contenv bash
# shellcheck shell=bash ##
# mclone mount for union over-shell-exec-command ##
##########################
# environment
source /config/env/rclone.env
config=/config/rclone/rclone-docker.conf
# rclone command

mclone mount remote: /mnt/remotes \
    --config=${config} \
    --log-file=/config/logs/rclone-union.log \
    --log-level=${LOGLEVEL} \
    --uid=${PUID} --gid=${PGID} --umask=${UMASK} \
    --allow-other --allow-non-empty \
    --timeout=1h --fast-list \
    --drive-pacer-min-sleep=1ms \
    --drive-use-trash=true --drive-pacer-burst=5000 \
    --cache-dir=${TMPRCLONE} \
    --no-modtime --no-seek \
    --transfers=4 \
    --ignore-errors --poll-interval=${POLL_INTERVAL} \
    --user-agent=${UAGENT} --no-checksum \
    --buffer-size=${BUFFER_SIZE} \
    --dir-cache-time=${DIR_CACHE_TIME} \
    --max-read-ahead=${MAX_READ_AHEAD} --vfs-read-ahead=${VFS_READ_AHEAD} \
    --vfs-cache-poll-interval=${VFS_CACHE_POLL_INTERVAL} \
    --vfs-cache-mode=${VFS_CACHE_MODE} \
    --vfs-cache-max-age=${VFS_CACHE_MAX_AGE} \
    --vfs-cache-max-size=${VFS_CACHE_MAX_SIZE} \
    --drive-server-side-across-configs=true \
    --vfs-read-chunk-size-limit=${VFS_READ_CHUNK_SIZE_LIMIT} \
    --vfs-read-chunk-size=${VFS_READ_CHUNK_SIZE} \
    --multi-thread-streams=25 --daemon
###EOF
EOF
## rclone union
value=/tmp/rcunion.union
if [[ -f ${value} ]];then rm ${value}; fi
IFS=$'\n'
filter="$1"
config=/config/rclone/rclone-docker.conf
mapfile -t mounts < <(eval mclone listremotes --config=${config} | grep "$filter" | sed '/union/d' | sed '/remote/d' | sed '/GDSA/d' | sort -r)
for i in ${mounts[@]}; do
   echo -n "$i " >> ${value}
done
sleep 2
mapfile -t mapped < <(eval cat ${value})
for i in ${mapped[@]}; do
   mclone config create remote union upstreams $i search_policy 'all' --config=${config}
done
##vfs-refresh
cat <<'EOF' > ${SRC}/union-rc-file.sh
#!/usr/bin/with-contenv bash
# shellcheck shell=bash ##
# mclone rc vfs/refresh for union over-shell-exec-command ##
##########################
# environment
source /config/env/rclone.env
config=/config/rclone/rclone-docker.conf
# rclone command

mclone rc vfs/refresh recursive=true \
       --rc-user=${RC_USER} --rc-pass=${RC_PASSWORD}  \
       --rc-addr=localhost:${RC_ADDRESS} \
       --config=${config} \
       --log-file=/config/logs/rc-refresh-union.log \
       --log-level=${LOGLEVEL_RC}
###EOF
EOF
chmod a+x ${SRC}/union-rc-file.sh && chown -hR abc:abc ${SRC}/union-rc-file.sh
chown -hR abc:abc ${TMPRCLONE}
log "-->> rclone rc refresh file created for union <<--"
#EOF#
