#!/usr/bin/with-contenv bash
# shellcheck shell=bash
function log() {
echo "[MERGERFS] ${1}"
}

log "-> Configure MergerFS || start <- [MERGERFS]"
rm -rf /tmp/mergerfs_version
curl -sX GET https://api.github.com/repos/trapexit/mergerfs/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' > /tmp/mergerfs_version
if [[ $(command -v mergerfs) == "" ]]; then
   echo "0" >/tmp/mergerfs_stored
else
   echo "$(mergerfs --version | awk '{print $3}')" >/tmp/mergerfs_stored
fi
if [[ `cat /tmp/mergerfs_version` != `cat /tmp/mergerfs_stored` ]]; then
   rm -rf /tmp/mergerfs_version && rm -rf /tmp/mergerfs
   curl -sX GET https://api.github.com/repos/trapexit/mergerfs/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' > /tmp/mergerfs_version
   log "-> Install now MergerFS Version `cat /tmp/mergerfs_version` <- [MERGERFS]"
   apk --quiet --no-cache --no-progress add \
      fuse libattr libstdc++ autoconf automake \
      libtool gettext-dev attr-dev linux-headers make build-base \
      fuse libattr libstdc++ git
   apk --no-cache update --quiet && apk --no-cache upgrade --quiet && apk --no-cache fix --quiet && rm -rf /var/cache/apk/*
   log "-> please hold the line ...... <- [MERGERFS]"
   rm -rf /tmp/mergerfs 1>/dev/null 2>&1
   git clone --quiet https://github.com/trapexit/mergerfs.git /tmp/mergerfs 1>/dev/null 2>&1 && cd /tmp/mergerfs && \
       git checkout --quiet `cat /tmp/mergerfs_version` -b local && make STATIC=1 LTO=1 1>/dev/null 2>&1 && make install 1>/dev/null 2>&1
   log "-> Yippee-ki-yay, motherfucker! it's done <- [MERGERFS]"
else
   log "-> latest version of MergerFS already installed  <- [MERGERFS]"
   log "-> latest version from trapexit `cat /tmp/mergerfs_version` <- [MERGERFS]"
fi
chown -R abc:abc $(command -v mergerfs)
chown -R abc:abc $(command -v mergerfs-fusermount)
chown -R abc:abc $(command -v mount.mergerfs)
chmod a+x $(command -v mergerfs)
chmod a+x $(command -v mergerfs-fusermount)
chmod a+x $(command -v mount.mergerfs)
mgstored="$(mergerfs -v | grep 'mergerfs version:' | awk '{print $3}')"
log "-> Installed MergerFS Version $mgstored  <- [MERGERFS]"
sed -i 's/#user_allow_other/user_allow_other/' /etc/fuse.conf
log "-> Configure Mergerfs || done <- [MERGERFS]"
#>EOF<#
