#!/usr/bin/with-contenv bash
# shellcheck shell=bash
function log() {
echo "[Mount] ${1}"
}
log "-> update packages || start <-"
update="update upgrade fix"
for up2 in ${update};do
   apk --quiet --no-cache --no-progress $up2
done
apk del --quiet --clean-protected --no-progress
echo "@weekly bash /app/update-alpine/update-alpine.sh" > /tmp/crontab.conf
crontab /tmp/crontab.conf
rm -rf /var/cache/apk/*
log "-> update packages || done <-"
sleep 5
#>EOF<#
